var := "var"

var3 := "var3"

var1 = $(var)
var2 := $(var)
var3 ?= $(var)


var := "changed"

rule3:
	@echo "Phep gan = la phep gan de quy, nghia la khi var thay doi thi var1 cung se thay doi theo"	
	@echo "$(var1)"
	@echo "phep gan := la phep gan truc tiep" 
	@echo "$(var2)"
	@echo "?= la phep gan kiem tra xem var3 da duoc gan hay chua, chua thi gan cho var, roi thi khong lam gi"
	@echo "$(var3)"
rule1:
	echo "Hi im rule1"

rule2:
	@echo "Hi Im rule2"




